site_name: DarkEye

nav:
  - 首页: index.md
  - 入门指南: usage.md
  - 软件设置: settings.md
  - 版本更新记录: CHANGELOG.md
  - 开发准备: development.md
  - 常见问题: faq.md



plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["."]

markdown_extensions:
- admonition
- toc:
    permalink: true

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: 切换深色模式