from PySide6.QtWidgets import QWidget
from PySide6.QtGui import QColor
from PySide6.QtCore import Signal

class ColorWheelSimple(QWidget):
    colorChanged = Signal()
    def __init__(self, parent: QWidget | None = ...) -> None: ...

    def setL(self, l: float) -> None: ...
    def setC(self, c: float) -> None: ...
    def setH(self, h: float) -> None: ...

    def getL(self) -> float: ...
    def getC(self) -> float: ...
    def getH(self) -> float: ...

    def getCurrentColor(self) -> QColor: ...
    def getHexColor(self) -> str: ...

    def setHexColor(self, hex: str) -> None: ...
    def setInitialColor(self, hex: str) -> None: ...